#!/bin/bash

#------------------------------------------------------------------------------
# Wait for the network:
#------------------------------------------------------------------------------

[ "${WAIT_NETWORK}" ] && {

  local RETRIES=20

  echo '[Init] Waiting for the network...'

  while [ ${RETRIES} -gt 0 ]; do
    ip r 2> /dev/null | grep -q default && break
    sleep 1; RETRIES=$((RETRIES - 1))
  done

  [ ${RETRIES} -eq 0 ] && {
    echo '[Init] There is no network'
    exit 1
  }

  echo '[Init] A default gateway is present'
}

#------------------------------------------------------------------------------
# Configure the service:
#------------------------------------------------------------------------------

echo '[Init] Configuring the service...'

[ "${COREOS_CHANNEL}" ] && {
  sed -i "s/XXX-COREOS_CHANNEL-XXX/${COREOS_CHANNEL}/" /usr/sbin/datasync
}

[ "${SERVER_NAME}" ] && {
  sed -i "s/XXX-SERVER_NAME-XXX/${SERVER_NAME}/" /etc/httpd/conf/httpd.conf
  sed -i "s/XXX-SERVER_NAME-XXX/${SERVER_NAME}/" /etc/httpd/conf.d/25-data.conf
}

#------------------------------------------------------------------------------
# Run:
#------------------------------------------------------------------------------

echo "[Init] Executing: $*"
exec $*
