#!/bin/sh

#------------------------------------------------------------------------------
# Wait for the network:
#------------------------------------------------------------------------------

[ "$WAIT_IFACE" ] && {

  RETRIES=20

  echo "[Init] Waiting for ${WAIT_IFACE} network..."

  while [ $RETRIES -gt 0 ]; do
    ip a l dev $WAIT_IFACE | grep -q inet && break
    sleep 1; RETRIES=$((RETRIES - 1))
  done

  [ $RETRIES -eq 0 ] && {
    echo "[Init] There is no ${WAIT_IFACE} network"
    exit 1
  }

  echo "[Init] Interface ${WAIT_IFACE} is present"
}

#------------------------------------------------------------------------------
# Configure the service:
#------------------------------------------------------------------------------

echo '[Init] Configuring the service...'

[ "$SERVER_NAME" ] && {
  sed -i "s/XXX-SERVER_NAME-XXX/$SERVER_NAME/" /etc/httpd/conf/httpd.conf
  sed -i "s/XXX-SERVER_NAME-XXX/$SERVER_NAME/" /etc/httpd/conf.d/25-data.conf
}

#------------------------------------------------------------------------------
# Run:
#------------------------------------------------------------------------------

echo "[Init] Executing: $*"
exec $*
