#!/bin/bash

DOCROOT='/var/www/data'
COREOS_CHANNEL='XXX-COREOS_CHANNEL-XXX'

case $1 in

'base')
  [ -d ${DOCROOT}/centos/7/os/x86_64 ] || mkdir -p ${DOCROOT}/centos/7/os/x86_64
  rsync -av --delete --progress rsync://mirrors.kernel.org/centos/7/os/x86_64/ \
  ${DOCROOT}/centos/7/os/x86_64/
  ;;

'updates')
  [ -d ${DOCROOT}/centos/7 ] || mkdir -p ${DOCROOT}/centos/7
  reposync -r updates -d -p ${DOCROOT}/centos/7/ -n
  createrepo -c ${DOCROOT}/centos/7/updates/cachedir \
  --update ${DOCROOT}/centos/7/updates
  repoview -t updates ${DOCROOT}/centos/7/updates
  ;;

'extras')
  [ -d ${DOCROOT}/centos/7 ] || mkdir -p ${DOCROOT}/centos/7
  reposync -r extras -d -p ${DOCROOT}/centos/7/ -n
  createrepo -c ${DOCROOT}/centos/7/extras/cachedir \
  --update ${DOCROOT}/centos/7/extras
  repoview -t extras ${DOCROOT}/centos/7/extras
  ;;

'puppetlabs-products')
  [ -d ${DOCROOT}/puppet ] || mkdir -p ${DOCROOT}/puppet
  reposync -r puppetlabs-products -d -p ${DOCROOT}/puppet/ -n
  createrepo -c ${DOCROOT}/puppet/puppetlabs-products/cachedir \
  --update ${DOCROOT}/puppet/puppetlabs-products
  repoview -t puppetlabs-products ${DOCROOT}/puppet/puppetlabs-products
  [ -f ${DOCROOT}/puppet/RPM-GPG-KEY-puppetlabs ] || \
  wget -q http://yum.puppetlabs.com/RPM-GPG-KEY-puppetlabs -P ${DOCROOT}/puppet/
  ;;

'puppetlabs-deps')
  [ -d ${DOCROOT}/puppet ] || mkdir -p ${DOCROOT}/puppet
  reposync -r puppetlabs-deps -d -p ${DOCROOT}/puppet/ -n
  createrepo -c ${DOCROOT}/puppet/puppetlabs-deps/cachedir \
  --update ${DOCROOT}/puppet/puppetlabs-deps
  repoview -t puppetlabs-deps ${DOCROOT}/puppet/puppetlabs-deps
  [ -f ${DOCROOT}/puppet/RPM-GPG-KEY-puppetlabs ] || \
  wget -q http://yum.puppetlabs.com/RPM-GPG-KEY-puppetlabs -P ${DOCROOT}/puppet/
  ;;

'epel')
  [ -d ${DOCROOT}/centos/7 ] || mkdir -p ${DOCROOT}/centos/7
  reposync -r epel -d -p ${DOCROOT}/centos/7/ -n
  createrepo -c ${DOCROOT}/centos/7/epel/cachedir \
  --update ${DOCROOT}/centos/7/epel
  repoview -t epel ${DOCROOT}/centos/7/epel
  [ -f ${DOCROOT}/centos/7/epel/RPM-GPG-KEY-EPEL-7 ] || \
  wget -q http://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7 -P ${DOCROOT}/centos/7/epel/
  ;;

'coreos')
  [ -d ${DOCROOT}/coreos ] || mkdir -p ${DOCROOT}/coreos
  wget http://${COREOS_CHANNEL}.release.core-os.net/amd64-usr/current/coreos_production_qemu_image.img.bz2 \
  -O ${DOCROOT}/coreos/coreos_qemu.img.bz2
  ;;

'misc')
  [ -d ${DOCROOT}/centos/7 ] || mkdir -p ${DOCROOT}/centos/7
  reposync -r misc -d -p ${DOCROOT}/centos/7/ -n
  createrepo -c ${DOCROOT}/centos/7/misc/cachedir \
  --update ${DOCROOT}/centos/7/misc
  repoview -t misc ${DOCROOT}/centos/7/misc
  ;;

*)
  echo "Usage: ${0##*/} [base|updates|extras|puppetlabs-products|puppetlabs-deps|epel|coreos|misc]"
  ;;

esac
