#!/bin/sh

#------------------------------------------------------------------------------
# Wait for the network:
#------------------------------------------------------------------------------

RETRIES=20

while [ $RETRIES -gt 0 ]; do
  ip -o a | grep -q eth1 && break
  sleep 1; RETRIES=$((RETRIES - 1))
done

[ $RETRIES -eq 0 ] && {
  echo 'Where is the network?' && exit 1
}

#------------------------------------------------------------------------------
# Parse command line arguments:
#------------------------------------------------------------------------------

while [[ $# > 1 ]]; do

  key="$1"

  case $key in

    --server-name)
      SERVER_NAME="$2"
      shift
      ;;

    *) ;;

  esac

  shift

done

#------------------------------------------------------------------------------
# Configure the service:
#------------------------------------------------------------------------------

[[ -n $SERVER_NAME ]] && {
  sed -i "s/XXX-SERVER_NAME-XXX/$SERVER_NAME/" /etc/httpd/conf/httpd.conf
  sed -i "s/XXX-SERVER_NAME-XXX/$SERVER_NAME/" /etc/httpd/conf.d/25-data.conf
}

#------------------------------------------------------------------------------
# Run:
#------------------------------------------------------------------------------

exec /usr/sbin/httpd -DFOREGROUND
